module.exports=(sequelize,DataTypes)=>sequelize.define('flavors',{
    brand:{
        type:DataTypes.STRING,
        required:true
    },
    color:{
        type:DataTypes.STRING,
        required:false,
        defaultValue:"Black"
    }
});