module.exports=(sequelize,DataTypes)=>sequelize.define('favorites',{
    flavores:{
        type:DataTypes.STRING,
        required:true
    },
    calories:{
        type:DataTypes.INTEGER,
        required:false,
    }
});